{% set name = "pypots" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26159b7cb5538a41ae86903580f65f1ef5dbd31e76ae90c0e4bc97b41e4e67a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.23.3
    - scikit-learn >=0.24.1
    - pytorch >=1.11.0
    - scipy
    - tensorboard
    - pandas <2.0.0
    - h5py
    - pycorruptor
    - tsdb

test:
  imports:
    - pypots
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/WenjieDu/PyPOTS
  summary: A Python Toolbox for Data Mining on Partially-Observed Time Series
  description: |
    PyPOTS is born to become a handy toolbox that is going to make data mining on POTS easy rather than tedious, 
    to help engineers and researchers focus more on the core problems in their hands rather than on how to deal 
    with the missing parts in their data. PyPOTS will keep integrating classical and the latest state-of-the-art 
    data mining algorithms for partially-observed multivariate time series. For sure, besides various algorithms, 
    PyPOTS is going to have unified APIs together with detailed documentation and interactive examples across 
    algorithms as tutorials.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://pypots.readthedocs.io
  dev_url: https://github.com/WenjieDu/PyPOTS

extra:
  recipe-maintainers:
    - WenjieDu
