{% set name = "pypots" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7eb7b19b84745f458300788b84a7cbc92fd4043b634e6a226e0038fe588ced47

build:
  number: 0
  noarch: python
  script: |
    python -m pip install --upgrade pip
    pip install torch==1.13.1 -f https://download.pytorch.org/whl/cpu
    pip install pypots
    pip install torch-geometric torch-scatter torch-sparse -f "https://data.pyg.org/whl/torch-1.13.1+cpu.html"
    pip install -e ".[dev]"
    {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scikit-learn
    - pytorch >=1.10
    - scipy
    - tensorboard
    - pandas <2.0.0
    - h5py
    - pycorruptor
    - tsdb

test:
  imports:
    - pypots
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/WenjieDu/PyPOTS
  summary: 'A Python Toolbox for Data Mining on Partially-Observed Time Series'
  description: |
    PyPOTS is born to become a handy toolbox that is going to make data mining on POTS easy rather than tedious, 
    to help engineers and researchers focus more on the core problems in their hands rather than on how to deal 
    with the missing parts in their data. PyPOTS will keep integrating classical and the latest state-of-the-art 
    data mining algorithms for partially-observed multivariate time series. For sure, besides various algorithms, 
    PyPOTS is going to have unified APIs together with detailed documentation and interactive examples across 
    algorithms as tutorials.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://pypots.readthedocs.io
  dev_url: https://github.com/WenjieDu/PyPOTS

extra:
  recipe-maintainers:
    - WenjieDu
